version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on: 
      - zookeeper
    ports: 
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTIENCE: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres-producer:
    image: postgres:16
    environment:
      POSTGRES_DB: producerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]

  postgres-listener:
    image: postgres:16
    environment:
      POSTGRES_DB: listenerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: ["5433:5432"]
    command: >                         # ‚Üê THESE 3 LINES ARE CRITICAL
      postgres
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10

  cdc-producer:
    build: ./cdc-producer-service
    depends_on: [kafka, postgres-producer]
    ports: ["8080:8080"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-producer:5432/producerdb

  cdc-listener:
    build: ./cdc-listener-service 
    depends_on: [kafka, postgres-listener]
    ports: ["8081:8080"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-listener:5432/listenerdb

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash-pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - xpack.monitoring.enabled=false
    depends_on:
      - kafka
      - elasticsearch


  # ELASTICSEARCH + KIBANA
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    ports:
      - "5601:5601"
    depends_on: [elasticsearch]
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

volumes:
  listener_pg_data:
  es_data:
